# Generated by Django 4.1.1 on 2023-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_service_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('flavor', models.CharField(max_length=122)),
                ('Quantity', models.CharField(max_length=122)),
                ('Address', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
