# Generated by Django 4.1.1 on 2023-04-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_reserve_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=122)),
                ('Sphone', models.CharField(max_length=12)),
                ('pick', models.CharField(max_length=122)),
                ('Rname', models.CharField(max_length=122)),
                ('Rphone', models.CharField(max_length=12)),
                ('drop', models.CharField(max_length=122)),
                ('package', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
