# Generated by Django 4.1.1 on 2023-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_courier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='flavor',
            new_name='Item',
        ),
        migrations.AddField(
            model_name='orders',
            name='details',
            field=models.CharField(default='', max_length=122),
            preserve_default=False,
        ),
    ]
