# Generated by Django 4.1.1 on 2023-04-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_item_orders_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='item',
        ),
    ]
