# Generated by Django 4.1.1 on 2023-04-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_product_orders_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item',
            new_name='product',
        ),
    ]
